### ISSUE TITLE
Division by zero in get_angle function

### ISSUE THREAD

**Issue by Maliboue** [drkutuzov/glycocalyx-image-tools#1]
`get_angle` function cannot calculate the angle when x1 = x2 (Division by zero in `np.arctan((y2 -y1)/(x2 - x1))`).

Proposed solution:

replace 

return np.pi/2 - np.arctan((y2 -y1)/(x2 - x1))

with 

if x2 == x1:
        return 0
else:    
        return np.pi/2 - np.arctan((y2 -y1)/(x2 - x1))

**Comment by drkutuzov** [comment]
Thank you! Fixed
